### ISSUE TITLE
[Tag詳細ページ最終課題]Tag一覧ページからTag詳細ページに遷移させようとした際に出たエラーについて

### ISSUE THREAD

**Issue by Yuki0316** [shinonome-inc/qiita_client_yukiy#12]
## 概要
Tag一覧ページのGridViewにGestureDetectorをラップし、その中のonTap内にTagDetailListView(タグ詳細ページ)を設定、引数のtagName内にタグのidを指定することでタグ一覧から選択したタグの名前(id)とタグ詳細ページを紐づけられるのではないかと考え実装。
下記の内容を試してみましたがエラーが消えず15分以上経ってしまったのでissueにしました。
お手隙の際にご確認いただけると幸いです。

## エラー箇所
<img width="689" alt="スクリーンショット 2023-03-07 10 45 54" src="https://user-images.githubusercontent.com/102783724/223297942-41668d78-06d8-4a28-a01f-dc4a78b03070.png">
<img width="1054" alt="スクリーンショット 2023-03-07 10 45 30" src="https://user-images.githubusercontent.com/102783724/223297952-8f90489e-b8d5-4f2a-a7f5-05acf950890f.png">

## 試してみたこと
エラー文から検索し以下のページの内容を試してみた。
- [Error: The argument type 'Function?' can't be assigned to the parameter type 'void Function()?'](https://www.youtube.com/watch?v=YanWDEuISRI)
- [【Flutter】クラスでvoid関数を引数にすると「The argument type 'Function' can't be assigned to the parameter type 'void Function()?'.」とエラーが出る](https://qiita.com/yoshikoba/items/d143b6813d8812da23e5)
→17行目で定義しているtagの型をVoidCallBack?に変更、25行目のtagをtag!に変更
→エラー消えず
<img width="938" alt="スクリーンショット 2023-03-07 10 53 26" src="https://user-images.githubusercontent.com/102783724/223298830-416a3a5e-bd3d-4fe9-8d2d-33b4565e9d21.png">

- どちらもFunction型を変更しているのでTagDetailListPageや他のタグに関連するファイルを確かめてみたがFunction型がない
- 17行目の型をTagDetailListPageに変更
   →エラー消えず
<img width="929" alt="スクリーンショット 2023-03-07 11 00 26" src="https://user-images.githubusercontent.com/102783724/223299920-10834926-8cc2-4736-8bd7-16d8e26e5f8e.png">

**Comment by Yuki0316** [comment]
@KobayashiYoh さんに助けていただき解決できたのでアウトプットメモ
## エラー原因
- 型の不一致
ここは何度も躓きがちなので慣れてすぐ解決できるようにしていきたい。
onTapはVoid Function()?型なのに対し、TagDetailListPageはWidget型。
- onTapの書き方の問題
onTapはコロンの後に実装したい内容を書く。"onTap () {}"が正しい書き方。
- GestureDetectorの場所の問題
この場所にonTap内の実装を書いて実行したところ、GridView全体から遷移できるようになってしまった。一つ一つのセルからではなく、セルの間の空白部分をタップしても遷移できてしまう。
なのでTagGridViewCell.dart内に移動させてみたところ成功

### 修正後コード
<img width="874" alt="スクリーンショット 2023-03-07 12 58 47" src="https://user-images.githubusercontent.com/102783724/223317250-8d8590e8-c281-436c-9cc0-15b3d1e9fa5e.png">

**Comment by KobayashiYoh** [comment]
解決してよかったです🙌
