### ISSUE TITLE
[Tag詳細ページ最終課題]ページネーション・スクロールした際の灰色のパーツの挙動について

### ISSUE THREAD

**Issue by Yuki0316** [shinonome-inc/qiita_client_yukiy#14]
## 概要
お世話になります。Tag詳細ページの実装について下記2点の問題が発生しましたのでissueを作成します。試行錯誤してみましたが解決できませんでしたので、どなたかアドバイスよろしくお願い致します。
現時点までのPRです。
#13
## 問題点
- tag詳細ページにて新しい記事がUIに反映されない。コンソールを見てみるとTagPageNumberは更新されているが、Tag表示件数が更新されていない。feedPageで実装したコードをほぼそのままtag詳細ページにも実装したのにもかかわらず実行されない。
- 20件目の記事が通常時だと下に埋もれてしまって見えない。
※下記動画7秒~10秒地点、"Ruby忘備録# 1"という記事が通常時だと下に埋もれてしまう。

https://user-images.githubusercontent.com/102783724/224227693-eb96c056-d985-4824-ba31-76a2106a2138.mp4 

<img width="300" alt="スクリーンショット 2023-03-10 13 59 53" src="https://user-images.githubusercontent.com/102783724/224227894-01e097c1-0c71-4f8e-8d25-5fa99a3d2549.png">

- 記事一覧とappBarの間にある灰色の"投稿記事"と書かれたパーツ、figmaを見ると記事と一緒にスクロールできるようになっている。しかし、自分の実装したものは灰色のパーツをタップしてスライドさせると一緒にスクロールされるが、記事をタップしてスクロールすると灰色のパーツがついてこない。

https://user-images.githubusercontent.com/102783724/224230461-b8c7e73c-12d9-45cb-b767-77cca40c2ab0.mp4

## 試した内容
- tag_detail_list_pageのfutureBuilder内の見直し
<img width="607" alt="スクリーンショット 2023-03-10 14 38 31" src="https://user-images.githubusercontent.com/102783724/224232678-130d2242-9e41-4b75-b5dd-6d280eecff1f.png">

**Comment by mcz9mm** [comment]
一旦ここの動きは固定で大丈夫です
>記事一覧とappBarの間にある灰色の"投稿記事"と書かれたパーツ、figmaを見ると記事と一緒にスクロールできるようになっている。しかし、自分の実装したものは灰色のパーツをタップしてスライドさせると一緒にスクロールされるが、記事をタップしてスクロールすると灰色のパーツがついてこない。


```
      body: Column(
        children: [
          GreyArticlePart(),
          Expanded(
            child: FutureBuilder<List<Article>>(
```


もしやりたいのであれば、ListViewの0番目のところにColumnとして実装すると付いてくるようになるよ
futureTagDetailsのところのColumnを修正する。
```
      body: Center(
        child: FutureBuilder<List<Article>>(
          future: futureTagDetails,
          builder: (context, snapshot) {
```
ArticleListViewの方でGreyArticlePartを呼び出す（`listTile`は共通化したもの）
```
      itemBuilder: (BuildContext context, int index) {
        if (index == articles.length) {
          return _loadingView();
        }
        final article = articles[index];
        if (index == 0) {
          return Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              GreyArticlePart(),
              listTile(article, context),
            ],
          );
        }
        return listTile(article, context);
```

**Comment by mcz9mm** [comment]
`page=$pageNumber&page=1`
page=1は不要ではないかな？

```
 //タグ詳細
    String url =
        'https://qiita.com//api/v2/tags/$tagName/items?page=$pageNumber&page=1&per_page=20';
```

> tag詳細ページにて新しい記事がUIに反映されない。コンソールを見てみるとTagPageNumberは更新されているが、Tag表示件数が更新されていない。feedPageで実装したコードをほぼそのままtag詳細ページにも実装したのにもかかわらず実行されない。

**Comment by mcz9mm** [comment]
PRの方にもコメントしました
https://github.com/shinonome-inc/qiita_client_yukiy/pull/13#discussion_r1132132485

**Comment by Yuki0316** [comment]
> 一旦ここの動きは固定で大丈夫です
> 
> > 記事一覧とappBarの間にある灰色の"投稿記事"と書かれたパーツ、figmaを見ると記事と一緒にスクロールできるようになっている。しかし、自分の実装したものは灰色のパーツをタップしてスライドさせると一緒にスクロールされるが、記事をタップしてスクロールすると灰色のパーツがついてこない。
> 
> ```
>       body: Column(
>         children: [
>           GreyArticlePart(),
>           Expanded(
>             child: FutureBuilder<List<Article>>(
> ```
> 
> もしやりたいのであれば、ListViewの0番目のところにColumnとして実装すると付いてくるようになるよ futureTagDetailsのところのColumnを修正する。
> 
> ```
>       body: Center(
>         child: FutureBuilder<List<Article>>(
>           future: futureTagDetails,
>           builder: (context, snapshot) {
> ```
> 
> ArticleListViewの方でGreyArticlePartを呼び出す（`listTile`は共通化したもの）
> 
> ```
>       itemBuilder: (BuildContext context, int index) {
>         if (index == articles.length) {
>           return _loadingView();
>         }
>         final article = articles[index];
>         if (index == 0) {
>           return Column(
>             mainAxisSize: MainAxisSize.min,
>             children: [
>               GreyArticlePart(),
>               listTile(article, context),
>             ],
>           );
>         }
>         return listTile(article, context);
> ```

コメントに沿ってGreyArticlePartをArticleListView内で呼び出したところ正常に動作しました！

https://user-images.githubusercontent.com/102783724/224461393-c04804da-2dd2-4e12-b1f7-165c7c0d2d8b.mp4
