### ISSUE TITLE
[最終課題]Tagページ・ページネーションのエラーについて

### ISSUE THREAD

**Issue by Yuki0316** [shinonome-inc/qiita_client_yukiy#16]
## 概要
Tagページのページネーションを実装したのですが一部エラーが出てしまい、詰まってしまったのでissueを作成しました。お時間ある時で構いませんので、見ていただけると幸いです。
## 問題点
1. 無限スクロールと新規タグ取得はできているが、エラーが出る。
2. CircularProgressIndicatorの位置が真ん中ではなく左上に出る。

https://user-images.githubusercontent.com/102783724/224472139-f77ca393-9558-42f1-b63c-6c683a7f001f.mp4

<img width="611" alt="スクリーンショット 2023-03-11 16 42 56" src="https://user-images.githubusercontent.com/102783724/224472246-e2eb6993-d193-47f3-a586-1e5aff8132a7.png">

## 試してみたこと
- エラー文から[こちらのサイト](https://stackoverflow.com/questions/53967624/flutter-error-rangeerror-index-invalid-value-not-in-range-0-2-inclusive)を見つけ、itemCountに不備があるのかと考えましたが、TagPage.dartのTagGridView内に下記画像の通り書かれていました。
<img width="510" alt="スクリーンショット 2023-03-11 16 57 29" src="https://user-images.githubusercontent.com/102783724/224472593-558dab15-29d8-48a2-b7db-0b7c97f8710d.png">

- エラー文の"When the exception was thrown, this was the stack: "から問題の位置を特定しましたが、indexをどう変えればいいのかがわかりませんでした。
<img width="600" alt="スクリーンショット 2023-03-11 16 59 45" src="https://user-images.githubusercontent.com/102783724/224472781-a2deae6d-2371-4e32-8beb-979ab511ab3c.png">

<img width="707" alt="スクリーンショット 2023-03-11 17 01 36" src="https://user-images.githubusercontent.com/102783724/224472806-3c3c577b-395d-44fa-b1d2-02556f52d302.png">

**Comment by mcz9mm** [comment]
`final tag = tagList[index];`で存在しないindexにアクセスしてるのが原因です。
loadingが必要な時のitemLengthは`listTags.length + 1`なので、
itemBuilderで表示する最後の１つはLoading用のWidgetを返す必要があります。
```
      itemBuilder: (BuildContext context, int index) {
        final tag = tagList[index];
        return TagGridViewCell(
          tag: tag,
        );
      },
```


FeedPageでどうやってたか見るといいよ。
```
    return ListView.separated(
      controller: scrollController,
      itemCount: itemCount,
      itemBuilder: (BuildContext context, int index) {
        if (index == articles.length) {
          return _loadingView();
        }
        final article = articles[index];
        if (index == 0) {
          return Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              GreyArticlePart(),
              listTile(article, context),
            ],
          );
        }
        return listTile(article, context);
      },
```

**Comment by mcz9mm** [comment]
これはCenterWidget使えば良さそう？
> 2. CircularProgressIndicatorの位置が真ん中ではなく左上に出る。

**Comment by Yuki0316** [comment]
> `final tag = tagList[index];`で存在しないindexにアクセスしてるのが原因です。 loadingが必要な時のitemLengthは`listTags.length + 1`なので、 itemBuilderで表示する最後の１つはLoading用のWidgetを返す必要があります。
> 
> ```
>       itemBuilder: (BuildContext context, int index) {
>         final tag = tagList[index];
>         return TagGridViewCell(
>           tag: tag,
>         );
>       },
> ```
> 
> FeedPageでどうやってたか見るといいよ。
> 
> ```
>     return ListView.separated(
>       controller: scrollController,
>       itemCount: itemCount,
>       itemBuilder: (BuildContext context, int index) {
>         if (index == articles.length) {
>           return _loadingView();
>         }
>         final article = articles[index];
>         if (index == 0) {
>           return Column(
>             mainAxisSize: MainAxisSize.min,
>             children: [
>               GreyArticlePart(),
>               listTile(article, context),
>             ],
>           );
>         }
>         return listTile(article, context);
>       },
> ```

ご助言ありがとうございました！こちらArticleListViewのコードとよく見比べて解決できました！

**Comment by Yuki0316** [comment]
> これはCenterWidget使えば良さそう？
> 
> > 2. CircularProgressIndicatorの位置が真ん中ではなく左上に出る。

こちらFutureBuilderにCenterをラップしたところ最初に出てくるグルグルに関しては真ん中に出すことができたのですが、

<img width="400" alt="スクリーンショット 2023-03-15 17 06 26" src="https://user-images.githubusercontent.com/102783724/225247034-23d5c79f-9328-4e4d-b43f-0de40c01cf43.png">


次のタグをローディングする際のものは依然左に出てしまう状態です。
(動画3秒あたりに一瞬出てきます)

https://user-images.githubusercontent.com/102783724/225247020-b71b2637-1daa-40bd-81cf-d085b5542524.mp4

### 試したこと
その他変化がありそうな箇所にCenterを追加してみましたが、治りませんでした。
<img width="414" alt="スクリーンショット 2023-03-15 17 20 32" src="https://user-images.githubusercontent.com/102783724/225250303-02c965a4-08e4-481d-a6b3-754584079019.png">
<img width="473" alt="スクリーンショット 2023-03-15 17 22 26" src="https://user-images.githubusercontent.com/102783724/225250310-321d6155-c665-4811-98eb-ba12586acc1a.png">
