### ISSUE TITLE
WebViewを表示させる際のエラー文について

### ISSUE THREAD

**Issue by Yuki0316** [shinonome-inc/qiita_client_yukiy#4]
## 概要
web_view.dartを作成し、WebView表示をしようとしたところ、画像のようなエラーが出ました。
## 画像

<img width="500" alt="E21080E5-1AA0-4697-ABEE-E0849B9E8098" src="https://user-images.githubusercontent.com/102783724/209601137-bb285209-a9e9-4c67-8055-2b49b14946f8.png">

## 実装したい内容
[Flutter Web画面表示（進捗バー付き）](https://qiita.com/k2rt/items/77cbd77b486c1b825d3f)を参考にWeb画面表示を行った後、[Flutter モーダルボトムシート（iOS風）でWebView表示](https://qiita.com/k2rt/items/2711096ced3d4710f0ad)からモーダルを追加しようと考えています。

## 試したこと
[FlutterでWebView実装・JavaScript有効化](https://qiita.com/KatsuShin/items/3cdc985ac3993f47c523)の記事にあるSurfaceAndroidWebView();をAndroidWebView();の箇所と書き換えてみたが、エラー内容は変わらず。

エラー文から[Flutter: The getter isn't defined for the type](https://stackoverflow.com/questions/61832126/flutter-the-getter-isnt-defined-for-the-type)を見つけ、Answersをみたが、
> In the newer version of flutter, it has a class already named "Router" so only you have to give a different name to your class "Routes".
and then user Routes.homeScreenRoute to your main.dart file.

これを自分のコードでどう実装していいかわからず。

initialUrlのエラー文から[Flutter - named parameters aren't defined
](https://stackoverflow.com/questions/47582874/flutter-named-parameters-arent-defined)
> Android Studio Solution: Files > Invalidate Caches / Restart

Answersを試したが、効果なし。

## ソースコード
調べてみたところ、コミットしてプッシュしてからでないとソースコードを載せられない感じがするのですが、エラー文の状態でコミット、プッシュしてもいいのでしょうか？また他の方法があるのでしょうか？？

**Comment by KobayashiYoh** [comment]
`xx isn't defined`というエラーが何箇所か見受けられます。
定義されていないクラスやgetterなどを使おうとしているため、まずは`import`をしてあげる必要があります。

> エラー文の状態でコミット、プッシュしてもいいのでしょうか？また他の方法があるのでしょうか？？

人によって意見が分かれそうな気もしますが、今回のように質問のためであればpushまでしても大丈夫だと思います。（マージだけはダメ）
`git revert <コミットID>`というコマンドを使えば、commitを打ち消すことも可能なため、あまり気にしすぎなくても大丈夫だと思っています。
