### ISSUE TITLE
[質問・最終課題無限スクロール]新しい記事を取得するとpageNumberが3の倍数になり順番通り取得できないことについて

### ISSUE THREAD

**Issue by Yuki0316** [shinonome-inc/qiita_client_yukiy#7]
## 概要
FeedPage内での無限スクロールについて、新しい記事を取得することには成功したのですが、どうしてもpageNumberが1, 2, 3,...のように順番通りに取得されません。

## 問題点
記事を順番通りに取得できない。途中のページが飛ばされてしまう。

## 実装したい内容
新しい記事を順番通り取得する。

## 試した事
- FutureBuilder内のif文の中にある"pageNumber++;"を"pageNumber += 1;"に変更⇨解決せず
- ArticleListView内itemCountの見直し

## Console
<img width="500" alt="37FDEBBD-DB63-484D-9172-FAC8F6A41990" src="https://user-images.githubusercontent.com/102783724/221824856-6a5b0d7b-3b79-42db-9b2a-aa97cafa4257.png">

## 現在のUI
<video width="500" src="https://user-images.githubusercontent.com/102783724/221825255-28540185-61b4-4739-ab9e-78343ebc513a.mp4">

**Comment by ShuheiYoshidaJP** [comment]
`pageNumber++;`のpageNumberの更新直後にprint文はるのはどうですかね？
コードを見てないので、どうなっているのかが想像ができませんが…。
pageNumber is 1からpageNumber is 3が出力される間にpageNumber is 2の状態があるけど、
pageNumber is 2の状態の時は出力できてないのではと予想しています。

**Comment by Yuki0316** [comment]
> `pageNumber++;`のpageNumberの更新直後にprint文はるのはどうですかね？ コードを見てないので、どうなっているのかが想像ができませんが…。 pageNumber is 1からpageNumber is 3が出力される間にpageNumber is 2の状態があるけど、 pageNumber is 2の状態の時は出力できてないのではと予想しています。

返信ありがとうございます。pageNumberの更新直後ににprint文を貼ったところ、画像の通り、順番通り記事を取得できていることが確認できました。ありがとうございました！
<img width="278" alt="36F0F332-A5A1-43AF-A8C7-9EEEFEC186A8" src="https://user-images.githubusercontent.com/102783724/221841942-53f96c25-1c66-4a65-b310-b416e35e5066.png">

**Comment by ShuheiYoshidaJP** [comment]
解決できてよかったですが、fetchのタイミングが次の課題ですね。
pageNumber更新→fetch→pageNumber更新→fetch→pageNumber更新→fetch→pageNumber更新→fetch→pageNumber更新→fetch
にしたいですね。

**Comment by Yuki0316** [comment]
> 
画像の通り、print文の位置を修正したことでfetched→pageNumber更新の順にできました。
<img width="429" alt="623CA0CC-A35F-48D4-8AE7-0C0C20846C2A" src="https://user-images.githubusercontent.com/102783724/221845690-c4d18bd0-3df5-4113-aa76-7874c66388c0.png">
